apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatapp-deployment
  labels:
    app: tomcatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata:
      labels:
        app: tomcatapp 
    spec:
      imagePullSecrets:
      - name: gcr-json-key
          <!--Create gcr-json-key in Kubenetes controller with command
      kubectl create secret docker-registry gcr-json-key \
 --docker-server=nexus.vnext.vn:8082 \
 --docker-username=admin \
 --docker-password=123456 \
 --docker-email=thanhdv2287@gmail.com-->
 
      containers:
      - name: tomcatapp-server
        image: nexus.vnext.vn:8082/nexus.vnext.vn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: tomcatapp-service
spec:
  selector:
    app: tomcatapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31110
