apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatapp-deployment
  labels:
    app: tomcatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata:
      labels:
        app: tomcatapp 
    spec:
      containers:
      - name: tomcatapp-server
        image: 10.2.0.6:9001/10.2.0.6:latest
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: tomcatapp-service
spec:
  selector:
    app: tomcatapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31110
